-- Create a dedicated separate schema
create schema if not exists "gis";

-- enable the "postgis" extension
create extension postgis
with
	schema "gis";

create table if not exists public.restaurants (
	id int generated by default as identity primary key,
	name text not null,
	location gis.geography (POINT) not null
);

create index restaurants_geo_index on public.restaurants using GIST (location);

create or replace function restaurants_in_view (
	min_lat float,
	min_long float,
	max_lat float,
	max_long float
) returns table (
	id public.restaurants.id % TYPE,
	name public.restaurants.name % TYPE,
	lat float,
	long float
)
set
	search_path to '' language sql as $$
	select id, name, gis.st_y(location::gis.geometry) as lat, gis.st_x(location::gis.geometry) as long
	from public.restaurants
	where location operator(gis.&&) gis.ST_SetSRID(gis.ST_MakeBox2D(gis.ST_Point(min_long, min_lat), gis.ST_Point(max_long, max_lat)), 4326)
$$;

grant usage on schema gis to anon,
authenticated;
